name: Build WSA Magisk
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build WSA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build WSA
        run: |
          ./scripts/run.sh 
          ./scripts/build.sh
#       - name: Get current date
#         id: date
#         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/*
          overwrite: true


