name: Build WSA Magisk
on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    name: Build WSA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
        root: [magisk, none]
        
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y whiptail setools lzip wine winetricks patchelf e2fsprogs python3-pip aria2 p7zip-full attr
          pip list --disable-pip-version-check | grep -E "^requests " >/dev/null 2>&1 || python3 -m pip install requests
          winetricks list-installed | grep -E "^msxml6" >/dev/null 2>&1 || winetricks msxml6 || abort
          
      - name: Build WSA GAPPS ${{ matrix.root }} ${{ matrix.arch }}
        run:  ./scripts/build.sh --arch ${{ matrix.arch }} --release-type retail --magisk-ver stable --remove-amazon --root-sol ${{ matrix.root }} --compress --debug
    
      - name: Prepare release tag
        id: date
        run: echo "::set-output name=date::$(date +'v%Y-%m-%d')"

      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/*
          name: ${{ steps.date.outputs.date }}
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
          file_glob: true


