name: Build WSA Magisk
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build WSA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build WSA
        run: |
          sudo apt-get update
          sudo apt-get install -y whiptail setools lzip wine winetricks patchelf e2fsprogs python3-pip aria2 p7zip-full attr
          pip list --disable-pip-version-check | grep -E "^requests " >/dev/null 2>&1 || python3 -m pip install requests
          winetricks list-installed | grep -E "^msxml6" >/dev/null 2>&1 || winetricks msxml6 || abort
          ./scripts/build.sh --arch x64 --release-type retail --magisk-ver stable --gapps-brand none --gapps-variant pico --remove-amazon --root-sol magisk --compress --debug
#       - name: Get current date
#         id: date
#         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/*
          overwrite: true
          file_glob: true


