name: Build WSA Magisk
on: [workflow_dispatch]

jobs:
  build:
    name: Build WSA
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup WSL
        run: |
          wsl --install --distribution Ubuntu
          wsl --list --all
          wsl --status
          pwd && ls
          ./scripts/run.sh 
          ./scripts/build.sh

#       - name: Get current date
#         id: date
#         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/*
          overwrite: true


