name: Sync with upstream
on: 
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add remote upstream
        run: |
          git remote add upstream https://github.com/LSPosed/MagiskOnWSALocal
      - name: Merge upstream
        id: merge_upstream
        run: |
          git fetch upstream
          echo "::set-output name=merge_status::$(git log HEAD..upstream/master --oneline)"
          git checkout -b upstream
          git merge upstream/main
      - name: Merge to main
        run: |
          git checkout main
          git merge upstream-${{ github.sha }}
          git add .
          git diff --staged --quiet || git commit -am "🌍 Update JSON - $(date +'%d %b %Y | %I:%M %p')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
      - name: Create telegram alert for failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Merge upstream failed
            Origin: https://github.com/${{ github.repository }}
            Upstream: https://github.com/LSPosed/MagiskOnWSALocal
          
