name: Sync with upstream
on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: upstream
          fetch-depth: 0

      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: LSPosed/MagiskOnWSALocal    # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: main          # set the branch to merge to

      - name: Create telegram alert for failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Merge upstream failed
            Origin: https://github.com/${{ github.repository }}
            Upstream: https://github.com/LSPosed/MagiskOnWSALocal
