name: Sync with upstream
on: 
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add remote upstream
        run: |
          git remote add upstream https://github.com/LSPosed/MagiskOnWSALocal
      - name: Merge upstream
        id: merge_upstream
        run: |
          git fetch upstream
          echo "::set-output name=merge_status::$(git log HEAD..upstream/master --oneline)"
          git checkout -b upstream-${{ github.sha }}
          git merge upstream/master
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Merge to main
        run: |
          git checkout main
          git merge upstream-${{ github.sha }}

      - name: Push to origin
        if: success()
        uses: actions/github-auto-commit@v2
        with:
          commit_message: Merge upstream changes on ${{ steps.merge_upstream.outputs.date }}
          file_pattern: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
      - name: Create telegram alert for failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Merge upstream failed for https://github.com/${{ github.repository }} from https://github.com/LSPosed/MagiskOnWSALocal
          
